import{a as c,S as m,i as u}from"./assets/vendor-lDhL-8I6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function f(a){const o="49525829-4ad651e5c3f704318c87db2e9",s="https://pixabay.com/api/";try{return(await c.get(s,{params:{key:o,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){throw console.error("Error fetching images:",r),r}}function d(a){const o=t=>t.map(({webformatURL:n,largeImageURL:i,tags:l})=>`<li class="gallery-item">
              <a class="gallery-link" href="${i}">
                  <img
                      class="gallery-image"
                      src="${n}"
                      alt="${l.split(", ").slice(0,3).join(", ")}"
                  />
              </a>
            </li>`).join(""),s=document.querySelector(".form");let r=document.querySelector(".gallery");r||(r=document.createElement("ul"),r.className="gallery",s.insertAdjacentElement("afterend",r));const e=new m(".gallery a",{captionsData:"alt",captionDelay:250});r.innerHTML=o(a.hits),e.refresh()}const y=()=>{const a=document.querySelector(".form"),o=a.elements["search-text"];o.autocomplete="off",a.addEventListener("submit",s=>{s.preventDefault();const r=document.querySelector(".gallery");r&&r.remove();const e=document.createElement("p");e.className="gallery-message",e.textContent="Loading images, please wait...",a.insertAdjacentElement("afterend",e),f(o.value).then(t=>{t.totalHits?(e.remove(),d(t)):(e.remove(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}))})}),window.addEventListener("load",()=>{o.focus()})};y();
//# sourceMappingURL=index.js.map
